Repository hafiz1379/Catalog-of-my-things, pull requests merged in 2023-10, with the labels that each got.

#26 Feature/initial config
  .github/workflows/linters.yml
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: documentation, enhancement

#34 Catalog of my Things | Add Game and Author modules🎯
  app.rb
  json/games.json
  modules/author_module.rb
  modules/game_module.rb
Labels: documentation, enhancement, day_01

#35 Catalog of my Things | Preserving data on Music & Genre classes
  .rubocop.yml
  app.rb
  classes/genre.rb
  classes/music/load_music_genre.rb
  classes/music/save_music_genre.rb
  json/genres.json
  json/music_albums.json
Labels: json

#36 Catalog of my Things | Music & Genre - Unit Tests
  Gemfile
  app.rb
  spec/classes/music/genre_spec.rb
  spec/classes/music/load_music_genre_spec.rb
  spec/classes/music/music_album_spec.rb
  spec/classes/music/save_music_genre_spec.rb
Labels: Testing

#38 Catalog of my Things | SQL Schema - Music & Genre classes + main DB
  schema.sql
Labels: sql

#41 Catalog of my Things | Styling app
  .rubocop.yml
  Gemfile.lock
  app.rb
  classes/music/load_music_genre.rb
  json/books.json
  json/games.json
  json/genres.json
  json/music_albums.json
  modules/author_module.rb
  modules/book_module.rb
  modules/commands_module.rb
  modules/game_module.rb
  modules/label_module.rb
  modules/music_album_module.rb
  spec/classes/book/book_module_spec.rb
Labels: styling

#42 Ruby Group Capstone - Catalog of my things
  .github/workflows/linters.yml
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  app.rb
  assets/catalog_of_my_things_logo.png
  classes/author/author.rb
  classes/book.rb
  classes/game/game.rb
  classes/genre.rb
  classes/item.rb
  classes/label.rb
  classes/music/load_music_genre.rb
  classes/music/save_music_genre.rb
  classes/music_album.rb
  json/books.json
  json/games.json
  json/genres.json
  json/music_albums.json
  main.rb
  modules/author_module.rb
  modules/book_module.rb
  modules/commands_module.rb
  modules/game_module.rb
  modules/label_module.rb
  modules/music_album_module.rb
  schema.sql
  spec/classes/author/author_spec.rb
  spec/classes/book/book_module_spec.rb
  spec/classes/book/book_spec.rb
  spec/classes/game/game_spec.rb
  spec/classes/label/label_module_spec.rb
  spec/classes/label/label_spec.rb
  spec/classes/music/genre_spec.rb
  spec/classes/music/load_music_genre_spec.rb
  spec/classes/music/music_album_spec.rb
  spec/classes/music/save_music_genre_spec.rb
  spec/spec_helper.rb
Labels: documentation, mvp
